### PR TITLE
Fix smoke test

### PR DESCRIPTION
**Pull request by copacetic**
500 milliseconds is a flaky value. Timeout should be 1 second
to void flip floppitiness.

### CODE REVIEW

**Comment by SourenP** [comment]
Why did you make a test in node?
Can't this be done in cpp using catch?

Also isn't it flaky to check the output of the executable?
What if we change the string?

**Comment by copacetic** [comment]
I mentioned this in WhatsApp, but node is actually amazing for this because
it has asynchronous coding paradigms baked in, easy callbacks and streams
etc. It's also very fast to write JS instead of c++.

I also talked about the flakiness in WhatsApp 😂

**Comment by SourenP** [comment]
ship it?

**Comment by copacetic** [comment]
Hehe, we can revert it if you want, I developed on master by accident. You
should try using it

**Pull request merged**
